# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/example_nbs/test_export.ipynb.

# %% auto 0
__all__ = ['some_params', 'some_param', 'input_path', 'model_path', 'source_in_docs', 'function']

# %% ../../nbs/example_nbs/test_export.ipynb 2
from pathlib import Path

# %% ../../nbs/example_nbs/test_export.ipynb 3
# TODO: only dealing with simple params for now - scalars & string values
some_params = len([1, 2, 3])
some_param = "test"
input_path = str(Path(".").resolve())
model_path = str(Path(".").resolve().parent)

# %% ../../nbs/example_nbs/test_export.ipynb 5
# some other comment
def function():
    results = {"foo": 1}
    return results

# %% ../../nbs/example_nbs/test_export.ipynb 7
internal = True

# %% ../../nbs/example_nbs/test_export.ipynb 14
source_in_docs = True

# %% ../../nbs/example_nbs/test_export.ipynb 15
import time

time.sleep(1)

# %% ../../nbs/example_nbs/test_export.ipynb 17
import time

time.sleep(3)
