name: scilint_ci
on:
  [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ci 
        run: |
          set -ux
          wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
          sudo dpkg -i quarto*.deb
          scilint_ci
          if [ -f "_docs/index.html" ]; then
            echo "docs built successfully."
          else
            echo "index page not found in rendered docs."
            ls -la
            ls -la _docs
            exit 1
          fi
