name: scilint_ci
on:
  [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: settings.ini
      - name: ci
      - shell: bash 
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -U nbdev
          echo "Doing editable install..."
          test -f setup.py && pip install -e ".[dev]"
          echo "Check we are starting with clean git checkout"
          if [[ `git status --porcelain -uno` ]]; then
            git diff
            echo "git status is not clean"
            false
          fi
          wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
          sudo dpkg -i quarto*.deb
          scilint_ci
          if [ -f "_docs/index.html" ]; then
            echo "docs built successfully."
          else
            echo "index page not found in rendered docs."
            ls -la
            ls -la _docs
            exit 1
          fi
