name: publish 
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
      - name: release
	  - env: # Or as an environment variable
		pypi_user: ${{ secrets.PYPI_USER }}
		pypi_pwd: ${{ secrets.PYPI_PWD }}
        run: |
          scilint_ci --exclusions "nbs/example_nbs/"
		  echo "[pypi]" >> ~/.pypirc
		  echo "username = $pypi_user" >> ~/.pypirc
		  echo "password = $pypi_pwd" >> ~/.pypirc
		  nbdev_pypi
