name: publish
on:
  workflow_dispatch: null
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
      - name: release
        env:
          PYPY_USER: ${{ secrets.PYPI_USER }}
          PYPI_PWD: ${{ secrets.PYPI_PWD }}
        run: |
          scilint_ci --exclusions "nbs/example_nbs/"
          echo "[pypi]" >> ~/.pypirc
          echo "username = $pypi_user" >> ~/.pypirc
          echo "password = $pypi_pwd" >> ~/.pypirc
          nbdev_pypi

