name: publish
on:
  workflow_dispatch: null
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
      - name: release
        env:
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PWD: ${{ secrets.PYPI_PWD }}
        run: |
          scilint_ci --exclusions "nbs/example_nbs/"
          pip install twine
          echo "[pypi]" >> ~/.pypirc
          echo "repository = https://upload.pypi.org/legacy/" >> ~/.pypirc
          echo "username = $PYPI_USER" >> ~/.pypirc
          echo "password = $PYPI_PWD" >> ~/.pypirc
          nbdev_pypi
